### ISSUE TITLE
Allow sending persistent message to groups, channels & dms without inviting bot

### ISSUE THREAD

**Issue by cardoso** [RocketChat/Rocket.Chat.Apps-engine#41]
The only ways I found to send messages with Apps were:

Via User or Bot User. **Con:** They need to be added to groups & don't work on DMs
Via `notifyRoom()` or `notifyUser()`. **Con:** Messages are not persistent & say 'only you can see this message' even if you used `notifyRoom()`

I think we need an `APP` user type that can send messages in channels, groups & dms without having to be explicitly invited. 

Ref: https://github.com/cardoso/Rocket.Chat.Dropbox.Paper/issues/1

**Comment by timkinnane** [comment]
@cardoso That's a great idea. While you're thinking about it, can I link you to some related issues, because I'd really like a solution to be found for this in balance with the other concerns and hopefully simplify instead of add to the existing complications.

1. https://github.com/RocketChat/Rocket.Chat/issues/10456
2. https://github.com/RocketChat/Rocket.Chat/issues/9177
3. https://github.com/RocketChat/Rocket.Chat/issues/4016

**Comment by kaiiiiiiiii** [comment]
A must have for my app as well :)

**Comment by jrobeano** [comment]
Hi  Tim, my sincere apologies if this is very obvious... but were you able  to implement the notification in the SDK as you mentioned that you might? in https://github.com/RocketChat/Rocket.Chat/issues/9177

**Comment by d-gubert** [comment]
This is now possible! In the current app installation flow, the app receives a new user (with type `app`) that can send messages without being invited
