### ISSUE TITLE
http accessor doesn't throw on HTTP call error

### ISSUE THREAD

**Issue by d-gubert** [RocketChat/Rocket.Chat.Apps-engine#85]
When using the `http` accessor from inside an app, the methods availble do not throw an error in case of an http error.

In my case I was making a call to an invalid domain and the response was simply `null`.

Doing some research, it looks like this line is the reason why:
https://github.com/RocketChat/Rocket.Chat/blob/edbdc435ebcb77d66c20b530ee792c5122a47d63/packages/rocketchat-apps/server/bridges/http.js#L12

I think it would be better if the accessor threw an error and we let the app handle that situation

**Comment by graywolf336** [comment]
The reason behind this was that it forces the Apps to check the statusCode. And also, to ensure that this method returns the same thing no matter what happens. On top of that, it was done this way so that unexpected errors aren't thrown.

If the community wants to change to an error being thrown instead of how it currently is, then I think we need to schedule that for v2 as that is a major breaking change and I know some of the Apps currently out there would break if we change to this style - which we do not want happening (stability is one of the highest priorities).

**Comment by graywolf336** [comment]
Closing until we decide to take on a version two approach.
